### PR TITLE
create routes object

### PR DESCRIPTION
**Pull request by nathanielks**
Hey man!

I'm working on your idea to have a package for connecting Pouter with React specifically, so I'm exploring creating a single object that will be responsible for defining the routes.

### CODE REVIEW

**Comment by nathanielks** [comment]
My first question is: regarding route definitions: do we want the object to be a hierarchical structure (as it currently exists) or a flat object? I'm trying to think in the context of code-splitting. Having childRoutes would be helpful for nested views.

In all honesty, I'd love to replicate a lot of the features react-router provides, so I'm trying to combine the two ideas.

**Comment by nathanielks** [comment]
I'll be creating a React component that will handle this routes file later on, I just have to bounce to a meeting and wanted to get this in front of you before.

**Comment by tybro0103** [comment]
hmmmm, so the idea is to marry the url to both a route handler and a component? The router itself would then be responsible for rendering the right component... you'd then need a built-in `Router` component that takes the current url or `history` and renders the corresponding page component... which sounds kinda familiar ;) Now that react-router has added `onChange` I think there wouldn't be much difference.

The idea here is to have the router map the current location to a route handler, and the route handler decides which component to render (or redirect, or whatever). I think it'd be really neat to find a way to have the route handler return an component rather than a "page" string (later mapped to a component), but I can't think of a way to make that play nicely with Redux.

I do want to find a way to reduce the amount of "glue" code between Pouter and Redux/React, but so far, really haven't thought of anything.

As for nested views, I think it'd be really easy. Just change [the CurrentPage component](https://github.com/tybro0103/redux-universal-boilerplate/blob/master/app/components/routing/current-page.jsx#L25) to look more like:

```javascript
  render() {
    return {
      'inbox': <Inbox />,
      'message': <Inbox><Message /></Inbox>
    }[this.props.page];
  }
```

**Comment by tybro0103** [comment]
On second look, I see that it wouldn't be the router's responsibility to render the correct page, just that they were defined in the same place. Still though, I feel like it would be better to make it the responsibility of the route handler to pick the page component.

**Pull request closed without merging**
